package pdf

import (
	"bytes"

	"github.com/jung-kurt/gofpdf"
)

type CoAData struct {
	CoaNumber       string
	LotBusinessID   string
	BatchBusinessID string
	DocumentRef     string
	IssuedBy        string
	IssuedAt        string
	Status          string
	Moisture        *float64
	CupScore        *float64
	Grade           string
}

func RenderCoA(d CoAData) ([]byte, error) {
	var buf bytes.Buffer
	return writePDF(&buf, func(pdf *gofpdf.Fpdf) {
		heading(pdf, "CERTIFICATE OF ANALYSIS")
		line(pdf, "CoA Number:", d.CoaNumber)
		line(pdf, "Export Lot:", d.LotBusinessID)
		if d.BatchBusinessID != "" {
			line(pdf, "Batch:", d.BatchBusinessID)
		}
		if d.DocumentRef != "" {
			line(pdf, "Document Ref:", d.DocumentRef)
		}
		line(pdf, "Issued By:", d.IssuedBy)
		line(pdf, "Issued At:", d.IssuedAt)
		line(pdf, "Status:", d.Status)
		pdf.Ln(4)
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(0, 8, "Lab Results Summary")
		pdf.Ln(9)
		line(pdf, "Moisture:", fmtFloat(d.Moisture, "%"))
		line(pdf, "Cup Score:", fmtFloat(d.CupScore, "pts"))
		if d.Grade != "" {
			line(pdf, "Grade:", d.Grade)
		}
		footer(pdf, "Generated by IAG Quality Control (CUPPA LIMS). Official release requires completed certification workflow.")
	})
}
